name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew
    
    - name: Build with Gradle (Release)
      run: ./gradlew assembleRelease

    - name: Sign Apk
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
    
    - run: mv ${{steps.sign_app.outputs.signedReleaseFile}} ChainExplorer_$GITHUB_REF_NAME.apk
              
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        body: "Auto-generated release from CI."
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "*.apk"
